In [2]:
import zipfile
import os
import xml.etree.ElementTree as ET
import pandas as pd
from datetime import datetime

In [44]:

# Define file paths
# zip_file_path = "2023_TEOS_XML_04A.zip"  # Update with your actual file path
extract_folder = "extracted_files"

# Step 1: Ensure the extraction folder exists
# if not os.path.exists(extract_folder):
    # os.makedirs(extract_folder)  # Creates the folder if it does not exist

# Step 2: Extract ZIP file
# with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    # zip_ref.extractall(extract_folder)

# Step 3: List all extracted XML files
xml_files = [f for f in os.listdir(extract_folder) if f.endswith(".xml")]

# Step 4: Process XML files and extract relevant data
compensation_records = []

for file in xml_files:
    file_path = os.path.join(extract_folder, file)
    try:
        tree = ET.parse(file_path)
        root = tree.getroot()

        # Extract relevant sections
        return_data = root.find(".//{http://www.irs.gov/efile}ReturnData")
        return_header = root.find(".//{http://www.irs.gov/efile}ReturnHeader")

        if return_data is not None:
            # Extract Organization Name
            org_name_elem = return_header.find(".//{http://www.irs.gov/efile}Filer/{http://www.irs.gov/efile}BusinessName/{http://www.irs.gov/efile}BusinessNameLine1Txt")
            org_name = org_name_elem.text if org_name_elem is not None else "Unknown"

            # Extract Employer Identification Number (EIN)
            ein_elem = return_header.find(".//{http://www.irs.gov/efile}Filer/{http://www.irs.gov/efile}EIN")
            ein = ein_elem.text if ein_elem is not None else "Unknown"

            # Extract Executive Compensation Details
            for person in return_data.findall(".//{http://www.irs.gov/efile}Form990PartVIISectionAGrp"):
                exec_name_elem = person.find(".//{http://www.irs.gov/efile}PersonNm")
                exec_name = exec_name_elem.text if exec_name_elem is not None else "Unknown"

                exec_title_elem = person.find(".//{http://www.irs.gov/efile}TitleTxt")
                exec_title = exec_title_elem.text if exec_title_elem is not None else "Unknown"

                base_comp_elem = person.find(".//{http://www.irs.gov/efile}ReportableCompFromOrgAmt")
                base_comp = base_comp_elem.text if base_comp_elem is not None else "0"

                bonus_comp_elem = person.find(".//{http://www.irs.gov/efile}BonusCompensationAmt")
                bonus_comp = bonus_comp_elem.text if bonus_comp_elem is not None else "0"

                other_comp_elem = person.find(".//{http://www.irs.gov/efile}OtherCompensationAmt")
                other_comp = other_comp_elem.text if other_comp_elem is not None else "0"

                total_comp_elem = person.find(".//{http://www.irs.gov/efile}TotalCompensationAmt")
                total_comp = total_comp_elem.text if total_comp_elem is not None else "0"

                # Append to structured data records
                compensation_records.append({
                    "Organization Name": org_name,
                    "EIN": ein,
                    "Executive Name": exec_name,
                    "Title": exec_title,
                    "Base Compensation ($)": base_comp,
                    "Bonus Compensation ($)": bonus_comp,
                    "Other Compensation ($)": other_comp,
                    "Total Compensation ($)": total_comp,
                    "Source File": file
                })

    except Exception as e:
        compensation_records.append({"Error": str(e), "Source File": file})

# Step 5: Convert to DataFrame
compensation_df = pd.DataFrame(compensation_records)

# Generate a timestamp for unique file naming
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

# Define the CSV filename with timestamp
csv_output_path = f"Executive_Compensation_{timestamp}.csv"

# Save the structured dataset as a CSV file
compensation_df.to_csv(csv_output_path, index=False)

print(f"Data extraction completed. CSV saved as: {csv_output_path}")

Data extraction completed. CSV saved as: Executive_Compensation_20250116_204131.csv

In [ ]:
arr = ['2023_TEOS_XML_05B']
# 2023_TEOS_XML_05B, 2023_TEOS_XML_11A, 2023_TEOS_XML_11B, 2023_TEOS_XML_11C
for x in arr:
  # Define file paths
  zip_file_path = f"{x}.zip"
  # zip_file_path = "2023_TEOS_XML_04A.zip"  # Update with your actual file path
  extract_folder = "extracted_files"

  # Step 1: Ensure the extraction folder exists
  if not os.path.exists(extract_folder):
      os.makedirs(extract_folder)  # Creates the folder if it does not exist

  # Step 2: Extract ZIP file
  with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
      zip_ref.extractall(extract_folder)

  # Step 3: List all extracted XML files
  xml_files = [f for f in os.listdir(extract_folder) if f.endswith(".xml")]

  # Step 4: Process XML files and extract relevant data
  compensation_records = []

  for file in xml_files:
      file_path = os.path.join(extract_folder, file)
      try:
          tree = ET.parse(file_path)
          root = tree.getroot()

          # Extract relevant sections
          return_data = root.find(".//{http://www.irs.gov/efile}ReturnData")
          return_header = root.find(".//{http://www.irs.gov/efile}ReturnHeader")

          if return_data is not None:
              # Extract Organization Name
              org_name_elem = return_header.find(".//{http://www.irs.gov/efile}Filer/{http://www.irs.gov/efile}BusinessName/{http://www.irs.gov/efile}BusinessNameLine1Txt")
              org_name = org_name_elem.text if org_name_elem is not None else "Unknown"

              # Extract Employer Identification Number (EIN)
              ein_elem = return_header.find(".//{http://www.irs.gov/efile}Filer/{http://www.irs.gov/efile}EIN")
              ein = ein_elem.text if ein_elem is not None else "Unknown"

              # Extract Executive Compensation Details
              for person in return_data.findall(".//{http://www.irs.gov/efile}Form990PartVIISectionAGrp"):
                  exec_name_elem = person.find(".//{http://www.irs.gov/efile}PersonNm")
                  exec_name = exec_name_elem.text if exec_name_elem is not None else "Unknown"

                  exec_title_elem = person.find(".//{http://www.irs.gov/efile}TitleTxt")
                  exec_title = exec_title_elem.text if exec_title_elem is not None else "Unknown"

                  base_comp_elem = person.find(".//{http://www.irs.gov/efile}ReportableCompFromOrgAmt")
                  base_comp = base_comp_elem.text if base_comp_elem is not None else "0"

                  bonus_comp_elem = person.find(".//{http://www.irs.gov/efile}BonusCompensationAmt")
                  bonus_comp = bonus_comp_elem.text if bonus_comp_elem is not None else "0"

                  other_comp_elem = person.find(".//{http://www.irs.gov/efile}OtherCompensationAmt")
                  other_comp = other_comp_elem.text if other_comp_elem is not None else "0"

                  total_comp_elem = person.find(".//{http://www.irs.gov/efile}TotalCompensationAmt")
                  total_comp = total_comp_elem.text if total_comp_elem is not None else "0"

                  # Append to structured data records
                  compensation_records.append({
                      "Organization Name": org_name,
                      "EIN": ein,
                      "Executive Name": exec_name,
                      "Title": exec_title,
                      "Base Compensation ($)": base_comp,
                      "Bonus Compensation ($)": bonus_comp,
                      "Other Compensation ($)": other_comp,
                      "Total Compensation ($)": total_comp,
                      "Source File": file
                  })

      except Exception as e:
          compensation_records.append({"Error": str(e), "Source File": file})

  # Step 5: Convert to DataFrame
  compensation_df = pd.DataFrame(compensation_records)

  # Generate a timestamp for unique file naming
  timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

  # Define the CSV filename with timestamp
  csv_output_path = f"Executive_Compensation_{timestamp}.csv"

  # Save the structured dataset as a CSV file
  compensation_df.to_csv(csv_output_path, index=False)

  print(f"Data extraction completed. CSV saved as: {csv_output_path}")

In [59]:
import os
import pandas as pd

# Path to the folder containing your CSV files
folder_path = 'excel_data'

# List to hold DataFrames from all CSV files
df_list = []

# Iterate over all files in the folder
for filename in os.listdir(folder_path):
    if filename.endswith('.csv'):  # Check if the file is a CSV
        file_path = os.path.join(folder_path, filename)
        
        # Read the CSV file into a DataFrame and append it to the list
        df = pd.read_csv(file_path)
        df_list.append(df)

# Concatenate all DataFrames into a single DataFrame
combined_df = pd.concat(df_list, ignore_index=True)

# Display the first few rows of the combined DataFrame
print(combined_df.head())

                       Organization Name        EIN  Executive Name  \
0                 POWERING POTENTIAL INC  473046472   JANICE LATHEN
1              EL CENTRO DE LAS AMERICAS  470658284  ROMEO J GUERRA
2           THE PARAMOUNT FOUNDATION INC  581837080  JENNIFER HAYES
3  AMERICAN FEDERATION OF GOVT EMPLOYEES  236463954     JAMES RIHEL
4  AMERICAN FEDERATION OF GOVT EMPLOYEES  236463954  JOSEPH MALIZIA

                Title  Base Compensation ($)  Bonus Compensation ($)  \
0           PRESIDENT                  61666                       0
1  EXECUTIVE DIRECTOR                  79192                       0
2  EXECUTIVE DIRECTOR                  79649                       0
3           PRESIDENT                   2100                       0
4      VICE-PRESIDENT                   1200                       0

   Other Compensation ($)  Total Compensation ($)  \
0                    3814                       0
1                    1075                       0
2                       0                       0
3                       0                       0
4                       0                       0

                     Source File  year
0  202300109349300000_public.xml  2023
1  202300109349300005_public.xml  2023
2  202300109349300050_public.xml  2023
3  202300109349300055_public.xml  2023
4  202300109349300055_public.xml  2023

In [60]:
combined_df.head()

,Organization Name,EIN,Executive Name,Title,Base Compensation ($),Bonus Compensation ($),Other Compensation ($),Total Compensation ($),Source File,year
0,POWERING POTENTIAL INC,473046472,JANICE LATHEN,PRESIDENT,61666,0,3814,0,202300109349300000_public.xml,2023
1,EL CENTRO DE LAS AMERICAS,470658284,ROMEO J GUERRA,EXECUTIVE DIRECTOR,79192,0,1075,0,202300109349300005_public.xml,2023
2,THE PARAMOUNT FOUNDATION INC,581837080,JENNIFER HAYES,EXECUTIVE DIRECTOR,79649,0,0,0,202300109349300050_public.xml,2023
3,AMERICAN FEDERATION OF GOVT EMPLOYEES,236463954,JAMES RIHEL,PRESIDENT,2100,0,0,0,202300109349300055_public.xml,2023
4,AMERICAN FEDERATION OF GOVT EMPLOYEES,236463954,JOSEPH MALIZIA,VICE-PRESIDENT,1200,0,0,0,202300109349300055_public.xml,2023

In [61]:
filtered_df = combined_df[
    (combined_df['Base Compensation ($)'] > 0) |
    (combined_df['Bonus Compensation ($)'] > 0) |
    (combined_df['Other Compensation ($)'] > 0)
]

filtered_df.head()

,Organization Name,EIN,Executive Name,Title,Base Compensation ($),Bonus Compensation ($),Other Compensation ($),Total Compensation ($),Source File,year
0,POWERING POTENTIAL INC,473046472,JANICE LATHEN,PRESIDENT,61666,0,3814,0,202300109349300000_public.xml,2023
1,EL CENTRO DE LAS AMERICAS,470658284,ROMEO J GUERRA,EXECUTIVE DIRECTOR,79192,0,1075,0,202300109349300005_public.xml,2023
2,THE PARAMOUNT FOUNDATION INC,581837080,JENNIFER HAYES,EXECUTIVE DIRECTOR,79649,0,0,0,202300109349300050_public.xml,2023
3,AMERICAN FEDERATION OF GOVT EMPLOYEES,236463954,JAMES RIHEL,PRESIDENT,2100,0,0,0,202300109349300055_public.xml,2023
4,AMERICAN FEDERATION OF GOVT EMPLOYEES,236463954,JOSEPH MALIZIA,VICE-PRESIDENT,1200,0,0,0,202300109349300055_public.xml,2023

In [62]:
filtered_df['year'] = '2023'

In [63]:
filtered_df.head()

,Organization Name,EIN,Executive Name,Title,Base Compensation ($),Bonus Compensation ($),Other Compensation ($),Total Compensation ($),Source File,year
0,POWERING POTENTIAL INC,473046472,JANICE LATHEN,PRESIDENT,61666,0,3814,0,202300109349300000_public.xml,2023
1,EL CENTRO DE LAS AMERICAS,470658284,ROMEO J GUERRA,EXECUTIVE DIRECTOR,79192,0,1075,0,202300109349300005_public.xml,2023
2,THE PARAMOUNT FOUNDATION INC,581837080,JENNIFER HAYES,EXECUTIVE DIRECTOR,79649,0,0,0,202300109349300050_public.xml,2023
3,AMERICAN FEDERATION OF GOVT EMPLOYEES,236463954,JAMES RIHEL,PRESIDENT,2100,0,0,0,202300109349300055_public.xml,2023
4,AMERICAN FEDERATION OF GOVT EMPLOYEES,236463954,JOSEPH MALIZIA,VICE-PRESIDENT,1200,0,0,0,202300109349300055_public.xml,2023

In [64]:
filtered_df.to_csv('../data/IRS_2023.csv', index=False)

In [65]:
import os
import pandas as pd

# Path to the folder containing your CSV files
folder_path = 'excel_data'

# List to hold DataFrames from all CSV files
df_list = []

# Iterate over all files in the folder
for filename in os.listdir(folder_path):
    if filename.endswith('.csv'):  # Check if the file is a CSV
        file_path = os.path.join(folder_path, filename)
        
        # Read the CSV file into a DataFrame and append it to the list
        df = pd.read_csv(file_path)
        df_list.append(df)

# Concatenate all DataFrames into a single DataFrame
irs_2024 = pd.concat(df_list, ignore_index=True)

In [66]:
irs_2024.head()

,Organization Name,EIN,Executive Name,Title,Base Compensation ($),Bonus Compensation ($),Other Compensation ($),Total Compensation ($),Source File
0,EUREKA HOUSING DEVELOPMENT CORPORATION,943303075,CHERYL CHURCHILL,Sec/Treasurer,0,0,31358,0,202402999349300000_public.xml
1,EUREKA HOUSING DEVELOPMENT CORPORATION,943303075,DUSTIN WIESNER,DIR. FIN.ADM.&TEC.,0,0,18351,0,202402999349300000_public.xml
2,EUREKA HOUSING DEVELOPMENT CORPORATION,943303075,KAY ESCARDA,President,0,0,0,0,202402999349300000_public.xml
3,EUREKA HOUSING DEVELOPMENT CORPORATION,943303075,KALI SEROTTA,VICE PRESIDENT,0,0,0,0,202402999349300000_public.xml
4,NEW HOPE FOR KIDS INC,591791345,DAVE JOSWICK,EXECUTIVE DI,71000,0,0,0,202402999349300005_public.xml

In [67]:
irs_2024_filtered = irs_2024[
    (irs_2024['Base Compensation ($)'] > 0) |
    (irs_2024['Bonus Compensation ($)'] > 0) |
    (irs_2024['Other Compensation ($)'] > 0)
]
irs_2024_filtered['year'] = '2024'
irs_2024_filtered.head()

C:\Users\Kartik\AppData\Local\Temp\ipykernel_36296\2627570883.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  irs_2024_filtered['year'] = '2024'

,Organization Name,EIN,Executive Name,Title,Base Compensation ($),Bonus Compensation ($),Other Compensation ($),Total Compensation ($),Source File,year
0,EUREKA HOUSING DEVELOPMENT CORPORATION,943303075,CHERYL CHURCHILL,Sec/Treasurer,0,0,31358,0,202402999349300000_public.xml,2024
1,EUREKA HOUSING DEVELOPMENT CORPORATION,943303075,DUSTIN WIESNER,DIR. FIN.ADM.&TEC.,0,0,18351,0,202402999349300000_public.xml,2024
4,NEW HOPE FOR KIDS INC,591791345,DAVE JOSWICK,EXECUTIVE DI,71000,0,0,0,202402999349300005_public.xml,2024
24,HEALTH TALENTS INTERNATIONAL INC,630738632,BODE TEAGUE,US MISSIONS,49379,0,0,0,202402999349300010_public.xml,2024
74,ST ANNE'S CREDIT UNION,42128094,BRUCE E FERNANDES,DIRECTOR/TREASURER/CLERK,16162,0,5539,0,202402999349300030_public.xml,2024

In [68]:
executive_df = pd.concat([filtered_df, irs_2024_filtered], ignore_index=True)
executive_df.head()

,Organization Name,EIN,Executive Name,Title,Base Compensation ($),Bonus Compensation ($),Other Compensation ($),Total Compensation ($),Source File,year
0,POWERING POTENTIAL INC,473046472,JANICE LATHEN,PRESIDENT,61666,0,3814,0,202300109349300000_public.xml,2023
1,EL CENTRO DE LAS AMERICAS,470658284,ROMEO J GUERRA,EXECUTIVE DIRECTOR,79192,0,1075,0,202300109349300005_public.xml,2023
2,THE PARAMOUNT FOUNDATION INC,581837080,JENNIFER HAYES,EXECUTIVE DIRECTOR,79649,0,0,0,202300109349300050_public.xml,2023
3,AMERICAN FEDERATION OF GOVT EMPLOYEES,236463954,JAMES RIHEL,PRESIDENT,2100,0,0,0,202300109349300055_public.xml,2023
4,AMERICAN FEDERATION OF GOVT EMPLOYEES,236463954,JOSEPH MALIZIA,VICE-PRESIDENT,1200,0,0,0,202300109349300055_public.xml,2023

In [74]:
executive_df[executive_df['year'] == '2024']

,Organization Name,EIN,Executive Name,Title,Base Compensation ($),Bonus Compensation ($),Other Compensation ($),Total Compensation ($),Source File,year
2280720,EUREKA HOUSING DEVELOPMENT CORPORATION,943303075,CHERYL CHURCHILL,Sec/Treasurer,0,0,31358,0,202402999349300000_public.xml,2024
2280721,EUREKA HOUSING DEVELOPMENT CORPORATION,943303075,DUSTIN WIESNER,DIR. FIN.ADM.&TEC.,0,0,18351,0,202402999349300000_public.xml,2024
2280722,NEW HOPE FOR KIDS INC,591791345,DAVE JOSWICK,EXECUTIVE DI,71000,0,0,0,202402999349300005_public.xml,2024
2280723,HEALTH TALENTS INTERNATIONAL INC,630738632,BODE TEAGUE,US MISSIONS,49379,0,0,0,202402999349300010_public.xml,2024
2280724,ST ANNE'S CREDIT UNION,42128094,BRUCE E FERNANDES,DIRECTOR/TREASURER/CLERK,16162,0,5539,0,202402999349300030_public.xml,2024
...,...,...,...,...,...,...,...,...,...,...
4668598,AGGIE REDROCK FOUNDATION,853580118,LAURENS SMITH,DIRECTOR (THRU 5/24),0,0,46096,0,Executive_Compensation_20250115_181214.csv,2024
4668599,AGGIE REDROCK FOUNDATION,853580118,JAMES Y TAYLOR,DIRECTOR (FROM 5/24),0,0,36586,0,Executive_Compensation_20250115_181214.csv,2024
4668600,VETERANS OF FOREIGN WARS OF THE UNITED,314332217,ERVIN YODER,QUARTERMASTER/ADJUTANT,50108,0,0,0,Executive_Compensation_20250115_181214.csv,2024
4668601,HANOVER HOME ASSOCIATION,230670840,MANDY BULLOCK,TREASURER,7200,0,0,0,Executive_Compensation_20250115_181214.csv,2024
4668602,HANOVER HOME ASSOCIATION,230670840,SHERRI SMALL,SECRETARY,7200,0,0,0,Executive_Compensation_20250115_181214.csv,2024

In [75]:
executive_df.to_csv('../data/Executive_IRS_2024_2023.csv', index=False)